### ISSUE TITLE
How to get the "stable" version with release branches?

### ISSUE THREAD

**Issue by rmzelle** [rtfd/readthedocs.org#1017]
https://docs.readthedocs.org/en/latest/versions.html says "We also create a stable version, if your project has any releases."

Is it possible to have the "stable" version if I'm using release branches, or does "stable" only work for release tags?

I currently have a "master" and "1.0.1" branch, but I don't see the option to build a "stable" version in my admin panel (I would like to have "/en/stable/" point to the "1.0.1" branch). How is this supposed to work, exactly? My docs are at http://docs.citationstyles.org/en/latest/.

**Comment by mboersma** [comment]
It's also unclear to me what a "release" means in version control terms here. Tag? Branch? GitHub release notes without the "pre-release" bit set?

**Comment by rmzelle** [comment]
I noticed that the RTD documentation was recently updated to clarify that the "stable" version is only available when there are "tagged releases". See https://github.com/rtfd/readthedocs.org/commit/c5f696edba17376c54747fed786f7346fafb54e6

That said, I pushed some tags to my repository, and I still don't see any option to build "stable". (see also https://github.com/rtfd/readthedocs.org/pull/1046#issuecomment-73639262 )

**Comment by tisdall** [comment]
I've had tags on my project for a while and I still don't see a "stable" option for my project either.  I think the original docs were set up before any tags were added, is it possible that it doesn't re-check after you've added tags?

**Comment by sloria** [comment]
I'm also unclear on how the `stable` branch is determined.

My project has the following branched

- 1.2-line : Latest stable release line
- dev : Development branch
- pypi: Latest release on PyPI

I also use git tags for releases.

I released a `2.0.0a1` version which is now on both the `dev` and `pypi` branch. The `stable` version on RTD shows up as the `2.0.0a1`. This is incorrect; I would expect it to show the latest release on the stable `1.2-line` branch.

Does RTD do any parsing of version numbers according to, e.g. semver.org or [PEP440](https://www.python.org/dev/peps/pep-0440/) to determine which is the stable branch? If not, it would be a nice feature to add. It would also be great if we could specify which git branch should be used for the `stable` version docs.

**Comment by gregmuellegger** [comment]
readthedocs basically goes through all the versions you see in the admin panel and takes the names there and parses them with [distlib](http://pythonhosted.org/distlib/). So all the strings like `'v1.0'`, `2.0.0a1` etc should work. Branch names like `master` will fail during parsing and then be left out when trying to figure out the available version numbers.

The distlib version in use is 0.1.2 which is quite old, so if some versions are parsed unexpectedly than that's probably the reason. distlib 0.1.2 is following PEP-386 for parsing, where as the "newer" Python community probably expects PEP-440.

@sloria I think your problem is directly related to that. Maybe we should upgrade the distlib library.

**Comment by gregmuellegger** [comment]
@rmzelle We have merged a change which might have fixed the problem with you not beeing able to build a staging version. Is this possible for you now?

**Comment by rmzelle** [comment]
I got it to work a while back (https://readthedocs.org/projects/citation-style-language/). Not sure how, but I did switch back and forth between GitHub repos, which might have done the trick.

**Comment by ericholscher** [comment]
Great :)
