### ISSUE TITLE
stable not updating after pushing new tag

### ISSUE THREAD

**Issue by fasaxc** [rtfd/readthedocs.org#2032]
## Details

I moved the `1.3.0` tag to point to the latest version of `1.3.0` but stable still rebuilds using the old `1.3.0` commit.  Rebuilding `1.3.0` does the right thing.

If this issue is for a specific project or build, include the following:
- Project: project-calico
- Build #: #3772260

**Comment by fasaxc** [comment]
Please can you give me a way to fix if stable ever builds the wrong thing?  Right now, as soon as the user makes an incorrect tag, it's broken forever.  Perhaps there could be a box in the admin UI to force stable to a particular commit?

The purity of the semver approach is nice in theory, but in practice, we all make mistakes!

**Comment by fasaxc** [comment]
I tried pushing a completely new 1.3.1 tag but stable still hasn't been updated, it still seems to be stuck on the old 1.3.0 tag.  Please can you investigate?

stable seems to be building commit e28b1cb9b1700ede2a69cc6bb81b690a008676a6
Even though 1.3.0 points at 93c8be150eb8b7335da77a655bf6db8affd803ee
and 1.3.1 points at (the even more recent) bf5a7ff586092fe21a4b4faaad3d6410e2db456e

**Comment by agjohnson** [comment]
Stable isn't updated because we don't have a `1.3.1` version. I can see if this is something on the server.

**Comment by jambonrose** [comment]
I'm seeing a similar issue.

I've set the `latest` docs to build the `development` branch. When I add a new tag to `development`, the `stable` doc section does not update to the new tag, and instead remains pointed to the previous tag.

In this case, I've just pushed a release for v0.5.0 of [django-improved-user](https://github.com/jambonsw/django-improved-user/). RTD shows me the new tag, and allows me to build docs for that tag without a problem. However, the `stable` docs sections continues to point at v0.4.0 (which is rather unhelpful, as there are no docs to be built then!).

I've tried manually building both `latest` and `stable`, but to no avail, and building `v0.5.0` worked fine, but had no effect on stable.

**Comment by jambonrose** [comment]
I'm poking around the codebase, but as it's brand new to me, so I'm a little lost. Happy to help here if you point me in the right direction.

Below is a screenshot of the issue I'm seeing. Note how the commit for `stable` (bottom) and `v0.4.0` are the same, but that RTD is seeing `v0.5.0`.

![screen shot 2017-08-26 at 22 37 15](https://user-images.githubusercontent.com/2659203/29746681-24cd28da-8ab0-11e7-9069-23155c767e36.png)

**Comment by jambonrose** [comment]
Welp. This is embarrassing. Found the answer in the [docs](http://docs.readthedocs.io/en/latest/versions.html#how-we-envision-versions-working): 'We only consider non pre-releases for the stable version of your documentation.' Whoops. I consider the issue solved.

**Comment by humitos** [comment]
A lot of work on how stable versions are handled were done in the last year. So I'd like to know, @fasaxc, if you still have this issue?

If you don't, please close the issue.

Thanks for your report!

**Comment by micheles** [comment]
I have a similar issue. I have released a new version of my decorator module (version 4.2.0) but `stable` is pointing to version 4.1.1, see http://decorator.readthedocs.io/en/stable/tests.documentation.html.
If I go to the page https://readthedocs.org/projects/decorator/versions/ I see that `stable` is indeed pointing to origin/4.1.1 and I cannot figure out how to change that.

**Comment by stsewd** [comment]
@micheles do you try manually building the latest version? (that way the version list is refreshed)

**Comment by micheles** [comment]
Yes, I tried but it does not work. At the end I turned "stable" into inactive status, since "latest" does what I expect (i.e. points to the latest version 4.2.1 which is stable anyway) and it is good enough for me.

**Comment by stsewd** [comment]
Related to #3729, and #3714. The users solve the problem by deleting the project and creating it again (same name can be used).

**Comment by pineapplemachine** [comment]
I am having a similar problem. However, in my case on the versions page it shows the correct commit even though visiting the "stable" docs still shows the docs from the previous v0.1.0 tag. I have verified that it is not a caching issue on my end.

![image](https://user-images.githubusercontent.com/7266412/38102313-8636d344-338b-11e8-976c-857898b0a096.png)

**Comment by stsewd** [comment]
@pineapplemachine can you provide the build url, and project?

**Comment by pineapplemachine** [comment]
@stsewd I fixed the problem a few minutes after posting! It was my own mistake, I had not rebuilt stable. (I wrongly assumed it would have rebuilt automatically) 

_Sent from my Samsung SAMSUNG-SM-G891A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by stsewd** [comment]
Everyone having this problem, it is a bug (more information on #3887). The current solution is recreating the project (the same name can be used)

**Comment by Peque** [comment]
Just for reference: I did not need to recreate the project. Simply re-building `latest` and `stable` made readthedocs.org pull the latest tag correctly.

**Comment by xylar** [comment]
I have been trying to get `stable` to build for my project, https://github.com/MPAS-Dev/MPAS-Analysis.  The project had tags `v0.43` and `v0.41` that should have been `v0.4.3` and `v0.4.1`.  I have renamed the tags (by creating new tags and deleting the old ones).  However, ReadTheDocs still sees the old  `v0.43` and `v0.41` tags even many hours later.  I tried deleting my ReadTheDocs project completely and recreating it but the tags remain.

It is likely that forks of my repo have these old tags still.  Could that somehow be the problem?

I am curious why there is not simply an option to force ReadTheDocs delete a version that the administrator knows to be invalid.

**Comment by stsewd** [comment]
@xylar please provide your Read the Docs project url

**Comment by stsewd** [comment]
I think I found your project https://readthedocs.org/projects/mpas-analysis/

Anyway, I just import your project on my local instance and seems to be ok

![screenshot-2018-5-21 versions read the docs](https://user-images.githubusercontent.com/4975310/40314090-180dca50-5cdd-11e8-8abe-5c3c8f5ca2ba.png)

If you are still having the problem you can try wiping the environment (this can be done in the `Versions` section, edit button)

**Comment by xylar** [comment]
@stsewd, yes, that is the correct URL for our project on ReadTheDocs.

> If you are still having the problem you can try wiping the environment (this can be done in the Versions section, edit button)

I tried wiping each unwanted environment with no effect.

I tried deleting the project and re-importing it, also with no effect.  Could something be cached on the ReadTheDocs side when I delete a project and bring it back?

**Comment by stsewd** [comment]
Hi, all people here, the fix for this bug was already deployed, can you test if that really solves your problem? (you may need to wipe and rebuild another version).

You may need to do some additional steps if that doesn't work https://github.com/rtfd/readthedocs.org/pull/3913#issuecomment-389228733
