### ISSUE TITLE
Protect against web/api 5xx responses

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2258]
When a build is attempted, but a web/api instance throws a 5xx response, a number of strange behaviors can result:

* Builds will get stuck in triggered state
* Builds will fail randomly when updating the api fails
* 5xx responses will be returned from the web servers to users

Part of the resolution to this may be defensive protection around intermittent 5xx responses. This may take some operation changes as well though, as our load balancer should really assume a 5xx response is enough to dislodge the server from the lb group.

Raised from #2255

**Comment by humitos** [comment]
The first one from the list is solved at #3312

I'm not sure to understand the resolution for this. If the request from the builder fails when hitting the API with a 5xx, what we can do?

**Comment by ericholscher** [comment]
I believe we should be able to have the build HTTP calls do a smart retry backoff. eg:

* Try call
* If it fails, try again
* If that fails, try again in 5s
* If that fails, try again in 10s
* If that fails, raise an exception

**Comment by humitos** [comment]
If that's the way to go, I suppose we could modify our [slumber client API class](https://github.com/rtfd/readthedocs.org/blob/afd7dd98c1d35d5f826ace6b29b1a89803523939/readthedocs/restapi/client.py#L39-L72) to do this magic. It would be IO blocking, but I suppose that would be fine.

@agjohnson labeled as `Operations` so he is maybe thinking in another thing.

**Comment by agjohnson** [comment]
Yeah, my original take on this is that if a server is overloaded, we should be detecting this and limiting traffic to the server. It's probably a sign that our web servers are overloaded.

Looks like this is still an issue after Azure move.

Retrying is probably a good first place to be defensive. :+1:
