### ISSUE TITLE
Git submodule error

### ISSUE THREAD

**Issue by barseghyanartur** [rtfd/readthedocs.org#3020]
## Details

* Project URL: https://readthedocs.org/projects/django-fobi/
* Build URL (if applicable): https://readthedocs.org/projects/django-fobi/builds/5767588/
* Read the Docs username (if applicable): delusionalinsanity

## Expected Result

*A description of what you wanted to happen*

I expected my documentation to be built.

## Actual Result

*A description of what actually happened*

Instead, I got this error:

Build failed
Error

Failed to import project: Failed to get code from 'https://github.com/barseghyanartur/django-fobi' (git clone): 1 git clone error output: Cloning into 'examples/wagtaildemo'... Permission denied (publickey).
 fatal: Could not read from remote repository. Please make sure you have the correct access rights and the repository exists. Clone of 'git@github.com:barseghyanartur/wagtaildemo.git' into submodule path 'examples/wagtaildemo' failed

**Comment by humitos** [comment]
Hi @barseghyanartur! It seems this problem is already solved since I can see some successful builds of your project. I'm closing this issue. Please, feel free to reopen it if you consider.

**Comment by barseghyanartur** [comment]
@humitos:

It's only because I have switched to BitBucket, which I use as alternative to GitHub for all my open source projects. There I use Mercurial (not Git) and I don't have Git sub-modules there. Thus, the problem remains. It's just I have found a work-around for myself (do not use Git sub-modules, in this particular case).

Simply put, if you try to generate docs (with Read the Docs) from [this](https://github.com/barseghyanartur/django-fobi) repository, you'll get the error.

I have no objections of you closing the issue, but there's a bug which isn't yet addressed.

**Comment by humitos** [comment]
@barseghyanartur thanks for your feedback.

I just import the repo you mentioned in my local instance of RTD and I wasn't able to reproduce this issue. The clone worked properly but it fails with another problem that seems to be tied to the repo itself, not RTD:

```
Exception occurred:
  File "conf.py", line 24, in <module>
    from nine.versions import DJANGO_LTE_1_7, DJANGO_GTE_1_8, DJANGO_GTE_1_7
ImportError: No module named nine.versions
```

Please, if you have a way to reproduce the issue let me know so I can work on it.

**Comment by barseghyanartur** [comment]
That's really weird. It fails on ``django-nine`` for you, which is a part of ``install_requires`` in the ``setup.py``.

In any case, I have just created another copy of the docs with GitHub as a source and guess what - it's passing now.

- http://django-fobi-github.readthedocs.io/en/latest/

I don't know what was it, but it seems to be fixed. Thanks for checking!

**Comment by humitos** [comment]
Thanks!

**Comment by barseghyanartur** [comment]
@humitos:

OK, another FYI update on the issue. I switched back from BitBucket to GitHub and it works, but:

I had to set the ``Programming Language`` (in ``Settings``) to ``Only Words`` (was ``Python``). Without the change it keeps failing.

**Comment by humitos** [comment]
Oh, that looks very strange.

Would you mine opening a new issue for that so we track this new error?

Thanks for the update! :)
