### ISSUE TITLE
Support Poetry

### ISSUE THREAD

**Issue by danielknell** [rtfd/readthedocs.org#4912]
It would be nice to be able to build docs for libraries managed with [poetry](https://poetry.eustace.io).

maybe  by checking for a `[tool.poetry]` section in `pyproject.toml`, having to keep a separate requirements.txt file in sync feels a bit fragile.

**Comment by stsewd** [comment]
What would be the poetry workflow in read the docs? Pipfile support will be out soon btw. If this gets implemented, it would live as an option in the configuration file.

**Comment by humitos** [comment]
So, replacing the `pip install` step by `poetry install` is all that's needed here or there are more tricks that I'm not seeing?

**Comment by sobolevn** [comment]
@humitos yes, I think so. 

Mind, that we also have to work with `venv` differently: we need to prefix all commands with `poetry run`.

**Comment by danielknell** [comment]
if you have the venv active, you can run `poetry install` and it will install into the current environment the same way that `pip install -r requirements.txt` will, you can then use the  venv as you would had normally.

`poetry run` is just a shorthand to run things in the venv without having to remember where it is or activate it first.

**Comment by stsewd** [comment]
> dev and prod dependencies

Is there a use case where users only want to install dev/prod deps? There are any other configurations that users may want to set?

**Comment by danielknell** [comment]
`poetry install` will install both dev and regular dependencies
`poetry install --no-dev` will install only regular dependencies and no dev stuff

the latter is more along the lines of `setup.py install` with the caveat that it wont install the module itself.

**Comment by uSpike** [comment]
I think this problem will resolve itself once the next version of `pip` is released with PEP-517 support (I've heard in January 2019?).  It was merged - https://github.com/pypa/pip/pull/5743
Then, a project only needs to add
```
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```
to the `pyproject.toml`, and the normal `pip install` should work.

**Comment by danielknell** [comment]
except the build script   runs `python setup.py install --force` by default instead of a `pip install .` so pep-517 wont come into play?

**Comment by stsewd** [comment]
@danielknell we do support installing the project using pip. 

@uSpike I have read the pip issue and pep, but I wasn't able to understand it very well yet :/ will this replace pipenv too?

**Comment by uSpike** [comment]
@stsewd using pip + pep-517 might be able to install from a `Pipfile` at some point in the future, but AFAIK it is not on the road map any time soon.

**Comment by GPMueller** [comment]
I'm not very familiar with Python virtual environments, but there may be another issue there.

I run poetry from a `conf.py` script, but get the following error, which I don't see how it could be fixed from user side:
```
Creating virtualenv clang-api-doc-py3.5 in /home/docs/.cache/pypoetry/virtualenvs
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/docs/.cache/pypoetry/virtualenvs/clang-api-doc-py3.5/bin/python', '-Im', 'ensurepip', '--upgrade', '--default-pip']
```

**Comment by sobolevn** [comment]
Since new `pip@19` is release, here's the short overview of what is going on.
I have locally checked how `pip@19` works with two setups: 

1. Application: https://github.com/wemake-services/wemake-django-template
2. Library: https://github.com/wemake-services/wemake-python-styleguide

## Application

Trying: `pip install .`
Result:

```        "No file/folder found for package {}".format(name)
    poetry.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package wemake-django-template

    ----------------------------------------
Command "/Users/sobolev/Documents/github/wemake-django-template/.venv/bin/python3 /Users/sobolev/Documents/github/wemake-django-template/.venv/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/qn/2gssw9hx48g81chw0398hlrr0000gn/T/tmpbzmmkx48" failed with error code 1 in /private/var/folders/qn/2gssw9hx48g81chw0398hlrr0000gn/T/pip-req-build-2qbtac_8
```

## Library

Trying: `pip install .`
Result: It installs everything as it should.

**Comment by danielknell** [comment]
does it work within rtfd? i keep meaning to try but have not found time to update my projects yet with the config to install via pip.

**Comment by uSpike** [comment]
@sobolevn I wouldn't expect https://github.com/wemake-services/wemake-django-template to install since it is a template (cookiecutter) project.

**Comment by sobolevn** [comment]
@uSpike `poetry install` works, so I had expected `pip install` to work as well.

**Comment by danielknell** [comment]
`poetry install` will only install dev/prod dependencies not the module itself
`pip install .` will try and install the module itself, and with it the prod dependencies. 

the fact it does not install dev dependencies is concerning and maybe pep 517 isn't enough to fully support poetry projects?

**Comment by sobolevn** [comment]
`poetry install` also installs the project itself in the editable mode. https://github.com/sdispater/poetry/releases/tag/0.12.0

**Comment by danielknell** [comment]
that means `poetry install` is equivalent to `pip install -e .`

**Comment by stsewd** [comment]
Can anyone try a project in rtd? We have the latest pip installed, let us know if there is anything else to do from our side to support poetry.

**Comment by uSpike** [comment]
@sobolevn that project (https://github.com/wemake-services/wemake-django-template) is a template, you're not supposed to `pip install` it.  The equivalent is having a `requirements.txt`, but they used poetry instead.  The actual project is inside https://github.com/wemake-services/wemake-django-template/tree/master/%7B%7Bcookiecutter.project_name%7D%7D but you must run cookiecutter to make it.

@danielknell aah I forgot about that... there might be a way to pass flags to poetry via pip?

**Comment by uSpike** [comment]
@danielknell I thought PEP-517 included some flags for pip to pass things to the backend: https://www.python.org/dev/peps/pep-0517/#config-settings

Those could then be caught by poetry in https://github.com/sdispater/poetry/blob/master/poetry/masonry/api.py and change how the dist is built, maybe to include dev dependencies?

**Comment by danielknell** [comment]
@lorinkoz 
```
# .readthedocs.yml
python:
   pip_install: true
```

**Comment by danielknell** [comment]
the only way forward i see at the moment unless using vanilla sphinx is to define anything sphinx needs as an optional dependencies, then add them to an extras group, then use a config like:

```
build:
    image: latest

python:
    version: 3.6
    pip_install: true
    extra_requirements:
        - docs
```

https://github.com/sdispater/poetry#extras

**Comment by uSpike** [comment]
@danielknell I agree, until https://github.com/pypa/pip/issues/5771 is done and poetry adds support for parsing said config to include dev dependencies in a build.

**Comment by lorinkoz** [comment]
Brief comment: `pip install -e` is not yet supported without a `setup.py`.

**Comment by lorinkoz** [comment]
I am getting the usual `Directory '.' is not installable. File 'setup.py' not found.` that makes me thing `-e` is being passed.

**Comment by sobolevn** [comment]
Yes, I understand that I can not install a project with `pip install .` without it being a library. But, my question remains: how is that possible to install my deps from `pyproject.toml` inside rtd?

In other words: how is that possible to replace `pip install -r requirements.txt` that is currently executed with something like `poetry install`?

**Comment by stsewd** [comment]
@sobolevn we don't support executing `poetry install`.

**Comment by danielknell** [comment]
@stsewd I am seeing failures, even though the project is setup to install via poetry and installs ok with `pip install .[docs]` locally it still fails because of no `setup.py` during build despite both reporting pip 19.0.1, is there any way it could be using a different pip in that step or something?

see:

build: https://readthedocs.org/projects/twelvefactor/builds/8456552/
code: https://github.com/artisanofcode/python-twelvefactor

**Comment by guillaumerenault** [comment]
[https://github.com/orsinium/poetry-setup](https://github.com/orsinium/poetry-setup ) can be used to generate a ```setup.py``` and ```requirements.txt``` while this is still a problem.

**Comment by lorinkoz** [comment]
What's the status of this? My docs started generating okay.

**Comment by sobolevn** [comment]
@lorinkoz can you please share your setup?

**Comment by lorinkoz** [comment]
Default setup in `readthedocs` regarding installing. My project only has a `pyproject.toml`. From the logs, RTD is not installing my dev dependencies, but in my case, they are not mandatory for building the docs.

**Comment by dmfigol** [comment]
I am `poetry` user as well and if I could store all dependencies in `pyproject.toml`, I'd be happy.
I am not sure that it is `poetry` job to change how they build the wheel with PEP517 API - I don't think they should include dev dependencies in the metadata.
Wouldn't it be possible to install `poetry` along with the `pip`, add some flag in `.readthedocs.yml` like `python.poetry_install=true` and then use `poetry install` in the project root after git checkout? This will install the project in editable mode with all dev dependencies.

**Comment by pawamoy** [comment]
I'm trying this again for [aria2p](https://github.com/pawamoy/aria2p).

Here is my RTD config:

```yaml
build:
    image: latest

python:
    version: 3.6
    pip_install: true

requirements_file: docs/requirements.txt
```

Previously, I had my own `aria2p` package in this requirement file to make it work:

```
sphinx==1.8.3
sphinx-rtd-theme==0.4.2
sphinxcontrib-spelling==4.2.0
toml==0.10.0
recommonmark==0.4.0
aria2p>=0.2.0
```

It means that the docs were built using the latest available release, not the local fetched code.

Today I changed it to `.`, to use the local code:

```
sphinx==1.8.3
sphinx-rtd-theme==0.4.2
sphinxcontrib-spelling==4.2.0
toml==0.10.0
recommonmark==0.4.0
.
```

It seems to work perfectly in a Docker container, but I get an error on RTD.

Docker session history (project root mounted on `/code`):

```
cd /code/
apt-get update
apt-get install python-enchant
pip install -U pip
pip install virtualenv
python -m virtualenv --no-site-packages --no-download VENV
/code/VENV/bin/python -m pip install --exists-action=w --cache-dir /root/.cache/pip -r docs/requirements.txt 
sphinx-build -E -b html docs build/docs
```

Error on RTD:

```console
$ /home/docs/checkouts/readthedocs.org/user_builds/aria2p/envs/latest/bin/python -m pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/aria2p/.cache/pip -r docs/requirements.txt
Processing /home/docs/checkouts/readthedocs.org/user_builds/aria2p/checkouts/latest
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/docs/checkouts/readthedocs.org/user_builds/aria2p/envs/latest/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-2d9t32el/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-2d9t32el/
```

It seems that `pip` is still searching for a `setup.py`. Could this be a cache problem?

Also this box in unchecked on RTD:

![screenshot_2019-03-03_13-52-10](https://user-images.githubusercontent.com/3999221/53695392-90db9880-3dbb-11e9-9381-9945a39b4e24.png)


By the way, the behavior is the same with or without `pip_install: true` in my RTD config.

**Comment by pawamoy** [comment]
Funny, I checked the box, rebuilt (failed), unchecked it again, rebuilt, and it completed!

It completed without `pip_install: true` in the config, and with `.` in `docs/requirements`. Then I tried again with the opposite: **with** `pip_install: true`, and **without** `.`: failed.

Forced-push back the previous config, which worked: failed.

Tried the check-uncheck trick, failed, failed.

I am lost :laughing:

**Comment by pawamoy** [comment]
One thing that could help debugging these kind of issues would be the ability to see the config used for the current build: the `readthedocs.yml` if any, and the settings from Admin:Settings and Admin:Advanced Settings.

To summarize, here are the things I tried:
- use a requirements.txt file for the docs, add your package in it: `my-package>=0.1.0`. It won't use the latest code, but the latest *release* (which is enough most of the time)
  :heavy_check_mark: **always worked**
- use a requirements.txt file for the docs, add `.` in it. Your package will be installed with `pip install .`, using poetry, and your latest version of the docs will be in sync with your master branch.
  :warning: **worked and failed, maybe cache issue**
- use a requirements.txt file for the docs, with only the dependencies for the docs. Add `pip_install: true` to the `python` section of your `readthedocs.yml` configuration file. Dependencies will be installed normally, then extra command `pip install .` will be run. It's like the previous solution, but in two steps.
  :exclamation:  **failed, maybe cache issue**

Of course, when RTD and poetry are more integrated together, the need for a requirements.txt could disappear.

My last question and I'll wait for feedback before continuing my flooding: is there a way to invalidate the build cache?

**Comment by stsewd** [comment]
> My last question and I'll wait for feedback before continuing my flooding: is there a way to invalidate the build cache?

Yes, you can wipe the environment before triggering a new build https://docs.readthedocs.io/en/stable/guides/wipe-environment.html

**Comment by pawamoy** [comment]
Yes! That did the trick, thank you :heart: Will edit my comments above

**Comment by agjohnson** [comment]
@rtfd/core discussed this a bit today -- and I've mostly only skimmed this issue just now -- but it sounds like `pip` will eventually support installation with poetry? If so, I think our stance at the moment is that we won't implement this in RTD directly, and instead wait for pip to support installation via poetry.

If there is anyone more intimately familiar with the plans of pip here, I think we'd still like input from you here. Our worry is spreading ourselves thin implementing more specific Python tooling, but we also don't want to support common tooling.

I'm going to close this issue for now, but I'm fine keeping this conversation going here if we need to re-evaluate this issue.

**Comment by stsewd** [comment]
###

**Comment by dmfigol** [comment]
@agjohnson 
`pip` already supports non-editable PEP-517 installs and this is why it is possible to use the following workaround:
```
---
build:
  image: latest

python:
  version: 3.6
  pip_install: true
  extra_requirements:
    - docs
```
However, there is an inconvenience: RTD dependencies like `sphinx` and other plugins should be listed as extras in `pyproject.toml`, which in turn will add this metadata to the published package on PyPi. Instead I'd prefer to keep these dependencies in `dev` section of `pyproject.toml` along with other dev tools like `pytest`, `flake8`, etc.  
To enable this workflow, RTD would need to install `poetry` and call `poetry install` instead of `pip install .[docs]` which could be controlled with some flag in `.readthedocs.yml`

**Comment by chrahunt** [comment]
The fundamental problem is that Poetry "dev dependencies" don't map directly to a concept that pip understands. `pip install` installs the package itself (+ any specified extras), which means only things listed as dependencies of the package make it into the virtual environment. At no point currently are dev dependencies considered actual dependencies except within poetry itself.

Users are not necessarily helpless though - I have published [`rtd-poetry`](https://github.com/chrahunt/rtd-poetry/) which should transparently download dev dependencies used in conjunction with the a `.readthedocs.yml` like:

```yml
---
build:
  image: latest

python:
  version: 3.6
  pip_install: true
```

It just checks whether you're on RTD and appends dev dependencies to the wheel metadata if so. I was able to use it successfully for my docs build [here](https://readthedocs.org/projects/quicken/builds/9016632/), but chrahunt/rtd-poetry#2 needs to be resolved before it is actually usable.

**Comment by thejohnfreeman** [comment]
@dmfigol is there an unstated assumption in your example? I tried the [`.readthedocs.yml`](https://github.com/thejohnfreeman/project-template-python/blob/master/.readthedocs.yml) you wrote, and it [didn't work for me](https://readthedocs.org/projects/project-template-python/builds/9024852/):

```yml
build:
  image: latest
python:
  version: 3.6
  pip_install: true
  extra_requirements:
    - docs
```

```
Processing /home/docs/checkouts/readthedocs.org/user_builds/project-template-python/checkouts/latest
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/docs/checkouts/readthedocs.org/user_builds/project-template-python/envs/latest/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-74uo7l0b/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-74uo7l0b/
```

**Comment by pawamoy** [comment]
You might need to wipe your build cache: https://docs.readthedocs.io/en/stable/guides/wipe-environment.html

**Comment by thejohnfreeman** [comment]
Wiping the environment did it. Thanks for the instructions, @pawamoy!

**Comment by jtpavlock** [comment]
I got the following to work for config v2

```yaml
# .readthedocs.yml

version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.6
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
```

```toml
# pyproject.toml

[tool.poetry.dependencies]
sphinx = {version = "^3", optional = true}

[tool.poetry.extras]
docs = ["sphinx"]
```

I'll echo @dmfigol's sentiment that this isn't ideal for reasons he stated.

**Comment by anentropic** [comment]
Just a +1 for @ jtpavlock method detailed above, it worked for me too.

Note that you need to have such packages listed both as `optional = true` in the main `tool.poetry.dependencies` and then again in the `extras > docs` list

**Comment by mforbes** [comment]
This approach still seems to have some issues.  In particular, if you use Poetry's support for logical or in dependences, then pip install from source fails with something like this:

```
pip._vendor.pkg_resources.RequirementParseError: Parse error at "'(>=3.4.2'": Expected stringEnd
```

```toml
# pyproject.toml

[tool.poetry.dependencies]
sphinx = {version = "^3.4.2|^4.3.0", optional = true}

[tool.poetry.extras]
docs = ["sphinx"]
```

One can of course get arround it with something ugly like

```toml
# pyproject.toml

[tool.poetry.dependencies]
sphinx = {version = ">=3.4.2,!=4.0.*,!=4.1.*,!=4.2.*,<5.0.0", optional = true}

[tool.poetry.extras]
docs = ["sphinx"]
```

**Comment by pawamoy** [comment]
For what it's worth, I think you should follow Python standards anyway, in this case PEP440, which does not include `x|y` or `^x` notations.

**Comment by Robpol86** [comment]
This is the approach I took to get readthedocs to run `poetry install`:

```yaml
# .readthedocs.yaml
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools: {python: "3.10"}
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    post_install:
      - poetry install

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
```

https://github.com/Robpol86/sphinx-multi-theme/blob/28aac0ac3bd54387bd51bfb9c673c2208394c729/.readthedocs.yaml

It looks like Poetry will install my dependencies into the virtualenv created by readthedocs if I set `virtualenvs.create=false`. Notice that I did not set `python.install` to prevent readthedocs from trying to pip install my project, since poetry install will do that instead.

**Comment by mondeja** [comment]
The following `build` config is working for me to install using a `doc` group with latest poetry:

```yaml
build:
  os: ubuntu-20.04
  tools:
    python: '3.10'
  jobs:
    post_install:
      - pip install poetry==1.2.0b1
      - poetry config virtualenvs.create false
      - poetry install --with doc
```

Note that currently installs other groups as well, but seems to have been fixed in master by https://github.com/python-poetry/poetry/pull/5338

**Comment by agjohnson** [comment]
Next question for Poetry users: I'm curious if we did add Poetry support to the build configuration feature, is that better or worse than copying a solution using `build.jobs.post_install`?

There are both advantages and disadvantages to this approach on our side, so we haven't been invested in making this a native feature.

**Comment by danielknell** [comment]
@agjohnson tbh, I opened this issue 4 years ago, found the work around to make things work, but it never really sat well with me, and the lack of real support for poetry resulted in me moving everything off readthedocs and self hosting instead ever since...

the post_install hacks are making me look again, but still not at the point it tips the scales and makes it worth the effort to migrate things back... (how do I know they won't stop working? installing poetry via pip is discouraged, etc)

some commitment that these approaches will always work going forward might eventually mean I move back...

but the following features in the config would probably have me tear up everything and move back in a heartbeat:

- being able to specify a poetry install instead of pip/setuptools
- ability to override the version of poetry the library needs (and getting that version or a later one)
- `extra_requirements` working with poetry

with the following being non essential but really nice to haves:

- optionally being able to specify dependency groups to install as in @mondeja example
- auto detection of poetry based on `pyproject.toml`

**Comment by danielknell** [comment]
@agjohnson unfortunately theres nothing really in pyproject.toml to say which version of poetry is needed...

but the example you posted looks like it would do everything needed.

---
i'll just note the following as its a bit confusing and non obvious unless you follow poetrys development closely....

poetry 1.2 (current beta) introduces the concept of "dependency groups" the default being the `standard` group and this is what ends up in wheels, or installable by pip via PEP-517, etc...

it replaces the old concept of dev dependencies (which are being deprecated), and means you can separate out non production dependencies into an arbitrary number of categories such as docs, tests, etc.

this is different to the extras which pip supports (the `pip install foo[bar,baz]` stuff), the extras all need to be defined in the `standard` dependency group and marked as optional.

`poetry install -E async` would be the equivalent of `pip install .[async]`

`poetry install --with docs` would install the main library dependencies with the additional `docs` dependency group but has no real analogy to pip

`poetry install -E async --with docs` would install the optional `async` extra dependencies with the library, but also install the extra poetry only dependencies specified in the "docs" dependency group.

**Comment by agjohnson** [comment]
> unfortunately theres nothing really in pyproject.toml to say which version of poetry is needed

Ah I thought you were referencing something like `build-system.requires`. Either way, there might be something here.

> i'll just note the following as its a bit confusing and non obvious unless you follow poetrys development closely.

And thanks again for another helpful overview. I might be the only core team member that uses Poetry consistently, but even my usage is mostly experimentation. So I'm certainly not up to speed on new features.

This is where I think most of the team has less appetite to support a new packaging tooling. We did go through this with Pip -- there are seemingly endless ways users use Pip. Coupled with the fact that we're not skilled with Poetry, it might be hard for us to support all of the usage patterns natively.

It's definitely a complex problem at our scale. We can't expect any specific version of Poetry, but that limits us from supporting features like dependency groups -- our implementation can't assume the user is using a modern Poetry.

**Comment by danielknell** [comment]
that would give you something like:

```
version: 2

python:
  install:
    - method: poetry
      extra_requirements:
        - foo
        - bar
```

translating into something like `POETRY_VIRTUALENVS_CREATE=false  poetry install -E foo -E bar` instead of `pip install .[foo,bar]`

**Comment by danielknell** [comment]
would an extension of the following with the snippet below work? 

https://github.com/readthedocs/readthedocs.org/blob/4ad6da0a7d613700a8c9273de6fdae1e95ebb46a/readthedocs/doc_builder/python_environments.py#L190-L224

```py
        elif install.method == POETRY:
            local_path = (
                os.path.join('.', install.path) if install.path != '.' else install.path
            )
            extra_req_param = ''
            if install.extra_requirements:
                extra_req_param = ["-E {}".format(v) for install.extra_requirements if v]
            self.build_env.run(
                'poetry',
                'install',
                *extra_req_param,
                cwd=os.path.join(self.checkout_path, local_path),
                bin_path="~/.local/bin",
                environment={
                  "VIRTUAL_ENV": self.venv_path(),
                  "PIP_NO_CACHE_DIR": "on",
                }
            )
```

I am probably missing something as I don't really know what I'm doing in this codebase, but it should be close enough for someone to roll with it?

it assumes a `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -` was previously run on the build system to install poetry into its default location, probably better to use `POETRY_HOME` but I can't remember how that works off the top of my head... passing VIRTUAL_ENV environment var should override poetrys internal venv management iirc and the `--no-cache-dir` from the pip branch can be forced with an environment var, then it just needs to run the command with cwd being the folder the `pyproject.toml` is in, so combining local and checkout path should work there?

**Comment by trim21** [comment]
you may need to use this:

```yaml
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - python -m pip install poetry
    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

sphinx:
  configuration: docs/conf.py
```
